""" BASIC
unlet! skip_defaults_vim
runtime defaults.vim
runtime xdg.vim

""" FILE
set undofile
set autoread
set hidden

""" EDITING
set nowrap
set breakindent
set list
set listchars=tab:\ \ ,trail:.,extends:~,precedes:~,nbsp:+
set virtualedit=block

""" INDENT
set shiftwidth=4
set softtabstop=-1
set expandtab
set autoindent
set smartindent

""" SEARCH
set hlsearch
set ignorecase
set smartcase

""" DISPLAY
set background=dark

let &t_EI = "\e[2 q"
let &t_SR = "\e[4 q"
let &t_SI = "\e[6 q"

""" KEYMAP
nnoremap <silent> <C-L> <C-L><Cmd>nohlsearch<CR>

""" PACKAGE
packadd! vim-oscyank
let g:oscyank_silent = 1
if (!has('clipboard_working'))
    let s:VimOSCYankPostRegisters = ['', '+', '*']
    let s:VimOSCYankOperators = ['y', 'd']
    function! s:VimOSCYankPostCallback(event)
        if index(s:VimOSCYankPostRegisters, a:event.regname) != -1
            \ && index(s:VimOSCYankOperators, a:event.operator) != -1
            call OSCYankRegister(a:event.regname)
        endif
    endfunction
    augroup VimOSCYankPost
        autocmd!
        autocmd TextYankPost * call s:VimOSCYankPostCallback(v:event)
    augroup END
endif
