runtime config/defaults.vim
runtime config/hier.vim

set autoread
set hidden
set virtualedit=block
set undofile

set tabstop=4
set expandtab
set shiftwidth=0
set softtabstop=-1

set autoindent
set smartindent

set hlsearch
set ignorecase
set smartcase

set nowrap
set breakindent

set laststatus=2
set number
set signcolumn=number
set list
set listchars=tab:\ \ ,trail:-,extends:>,precedes:<,nbsp:+

set sidescrolloff=5
set sidescroll=1

set termguicolors
set background=dark

"colo jellybeans

let &t_EI = "\e[2 q"
let &t_SR = "\e[4 q"
let &t_SI = "\e[6 q"

let mapleader=","

nnoremap <leader>q <Cmd>quit<CR>
nnoremap <leader>w <Cmd>write<CR>
nnoremap <leader>W <Cmd>w !sudo tee % >/dev/null<CR>

nnoremap <silent> <C-L> <C-L><Cmd>nohlsearch<CR>

packadd! oscyank
packadd! lexima
